### PR TITLE
fix(popover): using min-width for fit-size

### LINKED ISSUE #480: Using Popover component in Dropdown Button
Dropdown component should use Popover component in it to show action list

### PR DESCRIPTION
**Pull request by ogunb**
This PR implements using popover component inside dropdown component by replacing local implementation. To do that we needed to change `fit-size` behaviour of popover. If `fit-size` set, popover will have the minimum size of it's trigger element. If content will be larger, than popover will increase until it's max-width.

Fixes #480

### CODE REVIEW

File: src/components/dropdown/bl-dropdown.ts [hunk 1]
```diff
@@ -199,9 +147,9 @@ export default class BlDropdown extends LitElement {
       >
         ${this.label}
       </bl-button>
-      <div class="${popoverClasses}" role="menu" aria-expanded="${this.opened}">
+      <bl-popover .target="${this}" placement="bottom-start" @bl-popover-hide="${this.close}">
```
Comment (muratcorlu) [inline src/components/dropdown/bl-dropdown.ts:150]: Target should be the button above, not dropdown component itself.

Comment (ogunb) [reply src/components/dropdown/bl-dropdown.ts:150]: When I try to pass the target as the query result of the button, the popover component logs a warning because the button is not yet rendered, and the query result is null at initial render.

I checked the tooltip implementation PR, and it looks like the target is set on the popover with a show callback. We can implement it that way, if that's ok.

Comment (muratcorlu) [reply src/components/dropdown/bl-dropdown.ts:150]: Maybe it's time to try [`ref` directive](https://lit.dev/docs/templates/directives/#ref) of Lit, which is built for that kind of purposes. If it doesn't help, setting this lazily either in `firstUpdated` or just before showing it would also work.

**Comment by muratcorlu** [comment]
@ogunb There was an issue about chromatic tests that is also blocking pipelines of this PR. I merged the fix (#509). I merged next to this PR to use the fix. Please pull changes to your local.

File: src/components/dropdown/bl-dropdown.ts (hunk 1 above)
Comment (muratcorlu) [reply src/components/dropdown/bl-dropdown.ts]: LGTM. Please make your PR ready for review.

**Comment by muratcorlu** [comment]
Because now this PR is not just a refactor, and changes behaviour of popover component, I updated PR title and description accordingly.

**Review by muratcorlu — APPROVED** [review]
