### PR TITLE
fix(select): fix recurring space closing select box issue

### LINKED ISSUE #802: [BUG]: Baklava select input popover close event trigger problem
### Issue description

When typing in the bl select input, pressing the space bar causes the popover to close.

### Media & Screenshots

last

### Baklava Version

_No response_

### Operating system

_No response_

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

### PR DESCRIPTION
**Pull request by ogunb**
Keydown is triggered before input,
causing the select keydown handler to run first.

Fixes #802

### CODE REVIEW

**Review by buseselvi — APPROVED** [review]

File: src/components/select/bl-select.ts [hunk 1]
```diff
@@ -432,6 +432,11 @@ export default class BlSelect<ValueType extends FormValue = string> extends Form
                 ? searchbarPlaceholderText
                 : this.label || searchbarPlaceholderText}
               @input=${this._handleSearchOptions}
+              @keydown=${(e: KeyboardEvent) => {
+                if (e.code === "Space") {
+                  e.stopPropagation();
+                }
+              }}
```
Comment (ozkersemih) [inline src/components/select/bl-select.ts:439]: on line 576, there is a code block below. We can achieve same behaviour by updating that part of bl-select component.
```typescript
  private handleKeydown(event: KeyboardEvent) {
    if (this.focusedOptionIndex === -1 && ["Enter", "Space"].includes(event.code)) {
      this._togglePopover();
      event.preventDefault();
    }
...
```


if we don't to close popover when user press `Space`, we can achieve this behaviour by removing space in that array `(["Enter", "Space"])` in condition. Because probably we wanted to close popover our own, if now we dont want, we should update that condition I think. What do you think?

Comment (ogunb) [reply src/components/select/bl-select.ts:439]: Not closing the popover if nothing is focused makes sense to me too. @buseselvi what do you say?

**Review by ozkersemih — APPROVED** [review]

File: src/components/select/bl-select.ts (hunk 1 above)
Comment (ogunb) [reply src/components/select/bl-select.ts:439]: We'll discuss this further later.
